"""Source-tier helpers for market impact relationship graph lanes."""

from __future__ import annotations

from dataclasses import dataclass
from urllib.parse import urlparse

SOURCE_TIER_OFFICIAL = "official"
SOURCE_TIER_ISSUER_DISCLOSED = "issuer_disclosed"
SOURCE_TIER_EXCHANGE = "exchange"
SOURCE_TIER_REGULATOR = "regulator"
SOURCE_TIER_GOVERNMENT = "government"
SOURCE_TIER_LICENSED = "licensed"
SOURCE_TIER_INDUSTRY_ASSOCIATION = "industry_association"
SOURCE_TIER_WIKIDATA_BRIDGE = "wikidata_bridge"
SOURCE_TIER_REVIEWED_PROPOSAL = "reviewed_proposal"
SOURCE_TIER_LOCAL_PACK_METADATA = "local_pack_metadata"
SOURCE_TIER_TEST_FIXTURE = "test_fixture"
SOURCE_TIER_UNKNOWN = "unknown"

PROMOTION_ELIGIBLE_SOURCE_TIERS = {
    SOURCE_TIER_OFFICIAL,
    SOURCE_TIER_ISSUER_DISCLOSED,
    SOURCE_TIER_EXCHANGE,
    SOURCE_TIER_REGULATOR,
    SOURCE_TIER_GOVERNMENT,
    SOURCE_TIER_LICENSED,
    SOURCE_TIER_INDUSTRY_ASSOCIATION,
    SOURCE_TIER_REVIEWED_PROPOSAL,
    SOURCE_TIER_LOCAL_PACK_METADATA,
}

_OFFICIAL_HOST_FRAGMENTS = (
    "sec.gov",
    "companieshouse.gov.uk",
    "legislation.gov.uk",
    "parliament.uk",
    "federalregister.gov",
    "congress.gov",
    "eur-lex.europa.eu",
    "ecb.europa.eu",
    "iea.org",
    "worldbank.org",
    "opec.org",
    "pancanal.com",
    "usgs.gov",
    "eia.gov",
    "gleif.org",
    "leidata.gleif.org",
    "iso.org",
    "iso20022.org",
    "census.gov",
    "unstats.un.org",
    "ec.europa.eu",
    "eurostat.ec.europa.eu",
    "imf.org",
    "bis.org",
    "oecd.org",
    "world-exchanges.org",
    "wto.org",
    "fao.org",
    "ilo.org",
    "ojk.go.id",
    "setkab.go.id",
    "kemenkeu.go.id",
    "bumn.go.id",
    "boletinoficial.gob.ar",
    "datos.gob.ar",
    "indec.gob.ar",
    "rionegro.gov.ar",
    "crear.rionegro.gov.ar",
    "boletinoficial.rionegro.gov.ar",
    "data.gov.au",
    "rba.gov.au",
    "abs.gov.au",
    "ato.gov.au",
    "business.gov.au",
    "legislation.gov.au",
    "grants.gov.au",
    "firsthomebuyers.gov.au",
    "housingaustralia.gov.au",
    "cefc.com.au",
    "finance.gov.au",
    "arena.gov.au",
    "nrf.gov.au",
    "nsw.gov.au",
    "transport.nsw.gov.au",
    "gov.br",
    "bcb.gov.br",
    "opendata.bcb.gov.br",
    "api.bcb.gov.br",
    "bndes.gov.br",
    "agenciadenoticias.bndes.gov.br",
    "infrasa.gov.br",
    "ontl.infrasa.gov.br",
    "ppi.gov.br",
    "dados.gov.br",
    "ibge.gov.br",
    "ipeadata.gov.br",
    "bankofcanada.ca",
    "statcan.gc.ca",
    "canada.ca",
    "gazette.gc.ca",
    "laws-lois.justice.gc.ca",
    "ised-isde.canada.ca",
    "cib-bic.ca",
    "cgf-fcc.ca",
    "bdc.ca",
    "edc.ca",
    "natural-resources.canada.ca",
    "tc.canada.ca",
    "international.gc.ca",
    "cmhc-schl.gc.ca",
    "fcc-fac.ca",
    "agriculture.canada.ca",
    "competition-bureau.canada.ca",
    "pbc.gov.cn",
    "safe.gov.cn",
    "stats.gov.cn",
    "mof.gov.cn",
    "english.www.gov.cn",
    "www.gov.cn",
    "ndrc.gov.cn",
    "en.ndrc.gov.cn",
    "miit.gov.cn",
    "sasac.gov.cn",
    "en.sasac.gov.cn",
    "nfra.gov.cn",
    "samr.gov.cn",
    "cac.gov.cn",
    "nea.gov.cn",
    "mee.gov.cn",
    "english.mee.gov.cn",
    "nmpa.gov.cn",
    "english.nmpa.gov.cn",
    "mofcom.gov.cn",
    "english.mofcom.gov.cn",
    "most.gov.cn",
    "en.most.gov.cn",
    "chinamoney.com.cn",
    "bundesbank.de",
    "destatis.de",
    "bundesfinanzministerium.de",
    "bmwk.de",
    "bundesregierung.de",
    "bmvg.de",
    "bmdv.bund.de",
    "kfw.de",
    "unternehmensregister.de",
    "bundesanzeiger.de",
    "handelsregister.de",
    "govdata.de",
    "umweltbundesamt.de",
    "bmuv.de",
    "rbi.org.in",
    "mospi.gov.in",
    "finmin.gov.in",
    "financialservices.gov.in",
    "dipam.gov.in",
    "indiabudget.gov.in",
    "data.gov.in",
    "dpiit.gov.in",
    "meity.gov.in",
    "ism.gov.in",
    "heavyindustries.gov.in",
    "investindia.gov.in",
    "commerce.gov.in",
    "dgft.gov.in",
    "mpeda.gov.in",
    "pib.gov.in",
    "dot.gov.in",
    "cea.nic.in",
    "powermin.gov.in",
    "mnre.gov.in",
    "morth.nic.in",
    "nhai.gov.in",
    "mca.gov.in",
    "bancaditalia.it",
    "istat.it",
    "mef.gov.it",
    "dt.mef.gov.it",
    "mimit.gov.it",
    "mase.gov.it",
    "mit.gov.it",
    "cdp.it",
    "sace.it",
    "simest.it",
    "invitalia.it",
    "italiadomani.gov.it",
    "gazzettaufficiale.it",
    "registroimprese.it",
    "infocamere.it",
    "gse.it",
    "mercatoelettrico.org",
    "pagopa.it",
    "acn.gov.it",
    "salute.gov.it",
    "adm.gov.it",
    "banxico.org.mx",
    "inegi.org.mx",
    "hacienda.gob.mx",
    "finanzaspublicas.hacienda.gob.mx",
    "sat.gob.mx",
    "dof.gob.mx",
    "gob.mx",
    "datos.gob.mx",
    "cfe.mx",
    "pemex.com",
    "cenace.gob.mx",
    "proyectosmexico.gob.mx",
    "cbr.ru",
    "minfin.gov.ru",
    "rosstat.gov.ru",
    "government.ru",
    "roskazna.gov.ru",
    "economy.gov.ru",
    "nalog.gov.ru",
    "customs.gov.ru",
    "rosim.gov.ru",
    "minenergo.gov.ru",
    "minpromtorg.gov.ru",
    "mcx.gov.ru",
    "mintrans.gov.ru",
    "favt.gov.ru",
    "fsvps.gov.ru",
    "rkn.gov.ru",
    "rospotrebnadzor.ru",
    "my.gov.sa",
    "mof.gov.sa",
    "stats.gov.sa",
    "mep.gov.sa",
    "misa.gov.sa",
    "moenergy.gov.sa",
    "pif.gov.sa",
    "vision2030.gov.sa",
    "zatca.gov.sa",
    "gac.gov.sa",
    "mot.gov.sa",
    "mt.gov.sa",
    "haj.gov.sa",
    "moh.gov.sa",
    "mim.gov.sa",
    "sgs.gov.sa",
    "ncp.gov.sa",
    "neom.com",
    "redseaglobal.com",
    "qiddiya.com",
    "diriyah.sa",
    "roshn.sa",
    "visitsaudi.com",
    "gov.za",
    "treasury.gov.za",
    "statssa.gov.za",
    "sars.gov.za",
    "cipc.co.za",
    "dmre.gov.za",
    "energy.gov.za",
    "transport.gov.za",
    "eskom.co.za",
    "transnet.net",
    "transnetnationalportsauthority.net",
    "consilium.europa.eu",
)
_EXCHANGE_HOST_FRAGMENTS = (
    "nasdaq.com",
    "nyse.com",
    "londonstockexchange.com",
    "lse.co.uk",
    "asx.com.au",
    "tsx.com",
    "b3.com.br",
    "hkex.com.hk",
    "jpx.co.jp",
    "borsaistanbul.com",
    "cmegroup.com",
    "idx.co.id",
    "sgx.com",
    "deutsche-boerse.com",
    "boerse-frankfurt.de",
    "xetra.com",
    "stoxx.com",
    "six-group.com",
    "bseindia.com",
    "nseindia.com",
    "krx.co.kr",
    "twse.com.tw",
    "byma.com.ar",
    "open.bymadata.com.ar",
    "asxonline.com",
    "tmx.com",
    "money.tmx.com",
    "thecse.com",
    "sse.com.cn",
    "english.sse.com.cn",
    "query.sse.com.cn",
    "szse.cn",
    "cninfo.com.cn",
    "bse.cn",
    "csindex.com.cn",
    "hkexnews.hk",
    "borsaitaliana.it",
    "euronext.com",
    "live.euronext.com",
    "bmv.com.mx",
    "grupo-bmv.com.mx",
    "biva.mx",
    "moex.com",
    "iss.moex.com",
    "spimex.com",
    "spimex.global",
    "saudiexchange.sa",
    "tadawulgroup.sa",
    "jse.co.za",
    "clientportal.jse.co.za",
    "a2x.co.za",
)
_REGULATOR_HOST_FRAGMENTS = (
    "fca.org.uk",
    "sec.gov",
    "cftc.gov",
    "esma.europa.eu",
    "ofgem.gov.uk",
    "ofcom.org.uk",
    "cma.gov.uk",
    "epa.gov",
    "bankofengland.co.uk",
    "federalreserve.gov",
    "bis.org",
    "esma.europa.eu",
    "iosco.org",
    "mas.gov.sg",
    "sfc.hk",
    "asic.gov.au",
    "connectonline.asic.gov.au",
    "apra.gov.au",
    "tga.gov.au",
    "bcra.gob.ar",
    "cnv.gov.ar",
    "aif2.cnv.gov.ar",
    "cvm.gov.br",
    "sistemas.cvm.gov.br",
    "dados.cvm.gov.br",
    "antt.gov.br",
    "portal.antt.gov.br",
    "anp.gov.br",
    "aneel.gov.br",
    "anatel.gov.br",
    "sedarplus.ca",
    "securities-administrators.ca",
    "osc.ca",
    "ciro.ca",
    "osfi-bsif.gc.ca",
    "cer-rec.gc.ca",
    "crtc.gc.ca",
    "csrc.gov.cn",
    "chinaclear.cn",
    "sfc.hk",
    "bafin.de",
    "bundesnetzagentur.de",
    "bundeskartellamt.de",
    "bsi.bund.de",
    "bfarm.de",
    "pei.de",
    "kba.de",
    "lba.de",
    "eba.bund.de",
    "sebi.gov.in",
    "nsdl.co.in",
    "cdslindia.com",
    "trai.gov.in",
    "cercind.gov.in",
    "pngrb.gov.in",
    "cci.gov.in",
    "irdai.gov.in",
    "pfrda.org.in",
    "ibbi.gov.in",
    "cdsco.gov.in",
    "dgca.gov.in",
    "consob.it",
    "ivass.it",
    "covip.it",
    "arera.it",
    "agcom.it",
    "agcm.it",
    "aifa.gov.it",
    "enac.gov.it",
    "autorita-trasporti.it",
    "anticorruzione.it",
    "eba.europa.eu",
    "eiopa.europa.eu",
    "cnbv.gob.mx",
    "indeval.com.mx",
    "cofece.mx",
    "ift.org.mx",
    "cofepris.gob.mx",
    "cre.gob.mx",
    "cne.gob.mx",
    "antimonopolio.gob.mx",
    "resoluciones.antimonopolio.gob.mx",
    "ofac.treasury.gov",
    "sanctionsmap.eu",
    "mof.go.jp",
    "seco.admin.ch",
    "nsd.ru",
    "fas.gov.ru",
    "en.fas.gov.ru",
    "cma.org.sa",
    "cma.gov.sa",
    "sama.gov.sa",
    "edaa.com.sa",
    "muqassa.sa",
    "cst.gov.sa",
    "sfda.gov.sa",
    "gaca.gov.sa",
    "mawani.gov.sa",
    "waterregulator.gov.sa",
    "resbank.co.za",
    "fsca.co.za",
    "nersa.org.za",
    "icasa.org.za",
    "compcom.co.za",
    "comptrib.co.za",
    "strate.co.za",
)
_REGULATOR_URL_FRAGMENTS = (
    "gob.mx/cnbv",
    "gob.mx/cne",
    "gob.mx/cofepris",
    "gob.mx/cre",
    "gob.mx/ift",
    "gob.mx/antimonopolio",
    "gob.mx/crt",
    "gob.mx/atdt",
    "gob.mx/afac",
    "gob.mx/asea",
)
_LICENSED_HOST_FRAGMENTS = ("msci.com", "openfigi.com")
_INDUSTRY_ASSOCIATION_HOST_FRAGMENTS = ("semiconductors.org", "fifa.com")
_ISSUER_DISCLOSED_HOST_FRAGMENTS = (
    "pnm.co.id",
    "bri.co.id",
    "ir-bri.com",
    "bancopatagonia.com.ar",
    "bp.bancopatagonia.com.ar",
    "commbank.com.au",
    "bhp.com",
    "nab.com.au",
    "westpac.com.au",
    "anz.com.au",
    "macquarie.com",
    "woodside.com",
    "riotinto.com",
    "telstra.com.au",
    "colesgroup.com.au",
    "woolworthsgroup.com.au",
    "petrobras.com.br",
    "vale.com",
    "ri.bb.com.br",
    "itau.com.br",
    "bradescori.com.br",
    "ri.b3.com.br",
    "eletrobras.com",
    "ri.eletrobras.com",
    "weg.net",
    "ri.weg.net",
    "embraer.com.br",
    "ri.embraer.com.br",
    "rumolog.com",
    "ri.rumolog.com",
    "suzano.com.br",
    "ri.suzano.com.br",
    "klabin.com.br",
    "ri.klabin.com.br",
    "vibraenergia.com.br",
    "ri.vibraenergia.com.br",
    "ziliatech.com",
    "rbc.com",
    "td.com",
    "bmo.com",
    "scotiabank.com",
    "cibc.com",
    "shopify.com",
    "enbridge.com",
    "tcenergy.com",
    "cnrl.com",
    "suncor.com",
    "cn.ca",
    "cpkcr.com",
    "bce.ca",
    "telus.com",
    "rogers.com",
    "nutrien.com",
    "teck.com",
    "barrick.com",
    "loblaw.ca",
    "metro.ca",
    "corpo.metro.ca",
    "tencent.com",
    "alibabagroup.com",
    "walmart.com",
    "stock.walmart.com",
    "sap.com",
    "siemens.com",
    "telekom.com",
    "allianz.com",
    "rheinmetall.com",
    "db.com",
    "rwe.com",
    "eon.com",
    "basf.com",
    "bmwgroup.com",
    "mercedes-benz.com",
    "infineon.com",
    "mtu.de",
    "siemens-energy.com",
    "deutsche-boerse.com",
    "airbus.com",
    "npci.org.in",
    "bancamediolanum.it",
    "gruppobancobpm.it",
    "bancobpm.it",
    "gruppomps.it",
    "banca-mps.it",
    "unicreditgroup.eu",
    "intesasanpaolo.com",
    "mediobanca.com",
    "generali.com",
    "eni.com",
    "ferrari.com",
    "posteitaliane.it",
    "gruppotim.it",
    "terna.it",
    "snam.it",
    "italgas.it",
    "leonardo.com",
    "nexigroup.com",
    "finecobank.com",
    "bper.it",
    "femsa.com",
    "femsa.com.mx",
    "coca-colafemsa.com",
    "arcacontal.com",
    "arcaservices.com",
    "becle.com.mx",
    "cuervo.com.mx",
    "grupobimbo.com",
    "cemex.com",
    "americamovil.com",
    "gmexico.com",
    "walmex.mx",
    "walmex.com",
    "banorte.com",
    "inbursa.com",
    "bb.com.mx",
    "asur.com.mx",
    "aeropuertosgap.com.mx",
    "oma.aero",
    "volaris.com",
    "megacable.com.mx",
    "genommalab.com",
    "bmv.com.mx",
    "sberbank.com",
    "sberbank.ru",
    "rosneft.com",
    "novatek.ru",
    "lukoil.com",
    "polyus.com",
    "gazprom.com",
    "nornickel.com",
    "tatneft.ru",
    "phosagro.com",
    "severstal.com",
    "surgutneftegas.ru",
    "nlmk.com",
    "mts.ru",
    "magnit.com",
    "omz.ru",
    "omz.tech",
    "mechel.com",
    "rzd.ru",
    "transneft.ru",
    "rosatom.ru",
    "rostec.ru",
    "aramco.com",
    "saudiaramco.com",
    "sabic.com",
    "sabic-agrinutrients.com",
    "maaden.com.sa",
    "maaden.com",
    "acwapower.com",
    "saudielectricity.com",
    "se.com.sa",
    "stc.com.sa",
    "mobily.com.sa",
    "alrajhibank.com.sa",
    "alahli.com",
    "riyadbank.com",
    "almarai.com",
    "adesgroup.com",
    "arabdrill.com",
    "sal.sa",
    "flynas.com",
    "elm.sa",
    "naspers.com",
    "prosus.com",
    "standardbank.com",
    "firstrand.co.za",
    "capitecbank.co.za",
    "mtn.com",
    "vodacom.com",
    "sasol.com",
    "shopriteholdings.co.za",
    "remgro.com",
    "discovery.co.za",
    "sanlam.com",
    "aspenpharma.com",
    "telkom.co.za",
    "clicksgroup.co.za",
    "bidvest.com",
    "tfglimited.co.za",
    "picknpayinvestor.co.za",
    "lifehealthcare.co.za",
    "spar.co.za",
    "growthpoint.co.za",
    "absa.africa",
    "implats.co.za",
    "goldfields.co.za",
    "goldfields.com",
    "anglogoldashanti.com",
    "harmony.co.za",
    "sibanyestillwater.com",
    "northam.co.za",
)


@dataclass(frozen=True)
class SourceAttribution:
    source_name: str
    source_url: str
    source_snapshot: str
    source_tier: str
    promotion_eligible: bool


def _host(source_url: str) -> str:
    parsed = urlparse(source_url)
    return (parsed.netloc or "").casefold()


def _contains_any(value: str, fragments: tuple[str, ...]) -> bool:
    return any(fragment in value for fragment in fragments)


def classify_source_tier(source_name: str | None, source_url: str | None) -> str:
    """Classify a source into a coarse promotion tier without requiring new TSV columns."""

    name = (source_name or "").casefold()
    url = (source_url or "").strip()
    url_lower = url.casefold()
    host = _host(url)

    if not url:
        return SOURCE_TIER_UNKNOWN
    if url_lower.startswith("file://"):
        return SOURCE_TIER_LOCAL_PACK_METADATA
    if host.endswith(".test") or "example.com" in host or "example.test" in host:
        return SOURCE_TIER_TEST_FIXTURE
    if "wikidata" in host or "wikidata" in name:
        return SOURCE_TIER_WIKIDATA_BRIDGE
    if "reviewed proposal" in name or "reviewed-proposal" in name:
        return SOURCE_TIER_REVIEWED_PROPOSAL
    if "licensed" in name or "openfigi" in name or _contains_any(host, _LICENSED_HOST_FRAGMENTS):
        return SOURCE_TIER_LICENSED
    if _contains_any(host, _INDUSTRY_ASSOCIATION_HOST_FRAGMENTS):
        return SOURCE_TIER_INDUSTRY_ASSOCIATION
    if (
        _contains_any(host, _REGULATOR_HOST_FRAGMENTS)
        or _contains_any(url_lower, _REGULATOR_URL_FRAGMENTS)
        or "regulator" in name
    ):
        return SOURCE_TIER_REGULATOR
    if _contains_any(host, _EXCHANGE_HOST_FRAGMENTS) or "exchange" in name:
        return SOURCE_TIER_EXCHANGE
    if (
        host.endswith(".gov")
        or host.endswith(".gov.uk")
        or host.endswith(".gov.au")
        or host.endswith(".gov.cn")
        or host.endswith(".gov.ru")
        or _contains_any(host, _OFFICIAL_HOST_FRAGMENTS)
    ):
        return SOURCE_TIER_GOVERNMENT
    if (
        "investor" in name
        or "annual report" in name
        or "/investor" in url_lower
        or host.startswith("ir.")
        or _contains_any(host, _ISSUER_DISCLOSED_HOST_FRAGMENTS)
    ):
        return SOURCE_TIER_ISSUER_DISCLOSED
    return SOURCE_TIER_UNKNOWN


def build_source_attribution(
    *,
    source_name: str,
    source_url: str,
    source_snapshot: str,
) -> SourceAttribution:
    source_tier = classify_source_tier(source_name, source_url)
    return SourceAttribution(
        source_name=source_name,
        source_url=source_url,
        source_snapshot=source_snapshot,
        source_tier=source_tier,
        promotion_eligible=source_tier in PROMOTION_ELIGIBLE_SOURCE_TIERS,
    )


def validate_source_attribution(
    *,
    source_name: str | None,
    source_url: str | None,
    source_snapshot: str | None,
) -> list[str]:
    warnings: list[str] = []
    if not source_name:
        warnings.append("missing_source_name")
    if not source_url:
        warnings.append("missing_source_url")
    if not source_snapshot:
        warnings.append("missing_source_snapshot")
    if warnings:
        return warnings
    source_tier = classify_source_tier(source_name, source_url)
    if source_tier == SOURCE_TIER_UNKNOWN:
        warnings.append("unknown_source_tier")
    if source_tier == SOURCE_TIER_WIKIDATA_BRIDGE:
        warnings.append("bridge_source_requires_supporting_source_before_promotion")
    if source_tier == SOURCE_TIER_TEST_FIXTURE:
        warnings.append("test_fixture_source_not_promotable")
    return warnings
